## #ddev-generated
services:
    web:
        environment:
            - EXTENSION_KEY=xima_typo3_frontend_edit
            - EXTENSION_NAME=xima-typo3-frontend-edit
            - PACKAGE_NAME=xima/xima-typo3-frontend-edit
            - TYPO3_VERSIONS=13

            # TYPO3 v13 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Password1!
            - TYPO3_PROJECT_NAME=EXT:xima-typo3-frontend-edit Dev Environment
            - TYPO3_SERVER_TYPE=apache
